# =========== PEBSI CONFIGURATION FILE ===========
#
# This sample file shows some basic variables to
#         configure a PEBSI simulation.
# Any variables from params.py can be input here.
# 
# ================================================
#               SIMULATION METADATA
# ================================================
store_data: false
debug: true
output_fn: 'test_simulation'
start_date: '2024-04-20'
end_date: '2024-05-20'

# ================================================
#                SITE INFORMATION
# ================================================
rgi_id: '00.00000'
site: 'center'
glac_name: 'test'
timezone: 0
lat: 0
lon: 0

# ================================================
#                 CLIMATE OPTIONS
# ================================================
use_aws: true
aws_fn: 'data/sample_aws.csv'
aws_elev: 1500