name: pebsi-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - jax
  - optax
  - numpy<2
  - pandas
  - xarray
  - rioxarray
  - geopandas
  - pysolar
  - pytz
  - shapely
  - rasterio
  - netcdf4
  - zarr<3
  - dask
  - jupyter
  - joblib
  - scipy
  - matplotlib
  - tqdm
  - pytest
  - equinox