rgi_ids:
- '01.00570'
- '01.00570'
- '01.00570'
sites:
- A
- B
- D
n_points: 3
bias_vars:
- temp
start_date: '2000-04-20'
end_date: '2025-08-20'
dust_factor: 20
kp:
- 2.5
- 2.710018518732716
- 3.1900623202381246
albedo_ice:
- 0.2629926344927619
- 0.3315056238104315
- 0.4490959942340851
wind_factor:
- 1
- 2.0
- 2.0
option_accel_grains: true
option_flat_plates: false
debug: true
store_data: false
store_vars:
- MB
- EB
- layers
- climate
output_fp: ../Output/new_sims/
climate_fp: /Volumes/TOSHIBA EXT/
method_snicar: emulator
method_distribute: sites
